/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import BLL.BLLBan;
import BLL.BLLCTHD;
import BLL.BLLHoaDon;
import DTO.Ban;
import DTO.CTHD;
import DTO.HoaDon;
import DTO.KhachHang;
import DTO.NhanVien;
import DTO.ThucDon;
import Table.TableCustom;
import help.ChuyenDoi;
import help.MyCombobox;
import help.helper;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author NGUYEN VAN TRUONG
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    DefaultTableModel modeltblOrder;
    DefaultTableModel modeltblBan;
    Vector dsMonTungBan;
    String maNV = "";
    int rowBan = -1;
    
    public NhanVien login;
    
    public NhanVien getAccount(){
        return login;
    }
    
    public void setAccount(NhanVien login){
        this.login = login;
    }
    
    public void Table(){
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        TableCustom.apply(jScrollPane2, TableCustom.TableType.MULTI_LINE);
        TableCustom.apply(jScrollPane3, TableCustom.TableType.MULTI_LINE);
    }
    
    public Home() {
        initComponents();
        helper.clock(lbTime);
        txtGiamGia.setText("0");
        Table();
        Load();
        LoadCombobox();
        LoadListBan();
        modeltblOrder = (DefaultTableModel)tblOrder.getModel();
        modeltblBan = (DefaultTableModel)tblBanHD.getModel();
    }
    
    public void Authencation(NhanVien NVlogin){
        if(NVlogin != null) {
            if(NVlogin.getPHANQUYEN().equals("User")) {
                menuNhanVien.setVisible(false);
                menuThucDon.setVisible(false);
                menuThongKe.setVisible(false);
                menuBan.setVisible(false);
                menuLuongNV.setVisible(false);
            }
        }
    }

    Home(NhanVien nv) {
        initComponents();
        helper.clock(lbTime);
        txtGiamGia.setText("0");
        Table();
        Load();
        LoadCombobox();
        LoadListBan();
        Authencation(nv);
        modeltblOrder = (DefaultTableModel)tblOrder.getModel();
        modeltblBan = (DefaultTableModel)tblBanHD.getModel();
    }
    
    public void Load(){
        
        ArrayList<ThucDon> arrSP = BLL.BLLThucDon.GetAll();
        BLL.BLLThucDon.DoVaoTableThucDonHD(arrSP, tblThucDon);
        
        ArrayList<KhachHang> arrKH = BLL.BLLKhachHang.GetAll();
        BLL.BLLKhachHang.DoVaoComboboxKH(arrKH, cbbKhachHang);

        lbSoHD.setText(BLL.BLLHoaDon.TaoMaHD());
        dateNgayLapHD.setDate( new java.util.Date());  
    }
    
    public void LoadCombobox(){
//        ArrayList<LoaiMon> arrLSP = BLL.BLLLoaiMon.GetAll();
//        BLL.BLLLoaiMon.DoVaoCombobox(arrLSP, cbbLoaiMon);
    }
    
    void LoadListBan(){
        BLL.BLLBan.updateTinhTrang();
        modeltblBan = (DefaultTableModel) tblBanHD.getModel();
        for (Ban b : BLL.BLLBan.GetAll()) {
            cbbBan.addItem(b.getTENBAN());
        }
        dsMonTungBan = new Vector();
        modeltblBan.setRowCount(0);
        for (Ban b : BLL.BLLBan.GetAll()) {
            Vector r = new Vector();
            r.add(b.getMABAN());
            r.add(b.getTENBAN());
            r.add(b.getLOAIBAN());
            r.add(b.getTRANGTHAI());
            modeltblBan.addRow(r);
            dsMonTungBan.add(new Vector());
        } 
    }
    

    public static String tenmon = "";
    public static String giaban = "";
    public static int soluongmua = 0;
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanHD = new javax.swing.JTable();
        cbbBan = new javax.swing.JComboBox<>();
        btnChuyenBan = new button.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbSoHD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateNgayLapHD = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThucDon = new javax.swing.JTable();
        txtSearchMon = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        btnXoaMon = new button.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbMaNV = new javax.swing.JLabel();
        cbbKhachHang = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        lbTienPhaiTra = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        txtTienThua = new javax.swing.JLabel();
        btnPay = new button.JButton();
        lbStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchKH = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbBan = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbND = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuChangePass = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuNhanVien = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuKhachHang = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuThucDon = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuLuongNV = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuBan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuThongKe = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(195, 211, 192));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Bàn"));

        tblBanHD.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblBanHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bàn", "Tên bàn", "Loại bàn", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBanHD.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tblBanHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBanHDMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBanHD);

        cbbBan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbbBan.setBorder(null);

        btnChuyenBan.setText("Chuyển bàn");
        btnChuyenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbBan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(195, 211, 192));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Thông tin"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Số hóa đơn:");

        lbSoHD.setBackground(new java.awt.Color(195, 211, 192));
        lbSoHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSoHD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ngày lập:");

        dateNgayLapHD.setDateFormatString("dd-MM-yyyy");
        dateNgayLapHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbSoHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateNgayLapHD, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNgayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(195, 211, 192));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Thực đơn"));

        tblThucDon.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblThucDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên món", "Đơn vị", "Giá món"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThucDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblThucDonMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblThucDon);

        txtSearchMon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchMonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSearchMon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(txtSearchMon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(195, 211, 192));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("TỔNG TIỀN:");

        lbTongTien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbTongTien.setForeground(new java.awt.Color(255, 0, 0));
        lbTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTongTien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel6.setBackground(new java.awt.Color(195, 211, 192));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Danh sách món order"));

        tblOrder.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã món", "Tên món", "Số lượng", "Giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblOrder);

        btnXoaMon.setText("Xóa món");
        btnXoaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(btnXoaMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(195, 211, 192));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã nhân viên:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Bàn:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Khách hàng:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Giảm giá");

        lbMaNV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        cbbKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tiền phải trả:");

        lbTienPhaiTra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbTienPhaiTra.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Tiền khách đưa:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Tiền thừa:");

        txtTienKhachDua.setBackground(new java.awt.Color(195, 211, 192));
        txtTienKhachDua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTienKhachDua.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        txtTienThua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTienThua.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pay.png"))); // NOI18N
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tìm khách hàng:");

        txtSearchKH.setBackground(new java.awt.Color(195, 211, 192));
        txtSearchKH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchKH.setToolTipText("Nhập số điện thoại để tìm kiếm");
        txtSearchKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSearchKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKHKeyReleased(evt);
            }
        });

        txtGiamGia.setEditable(false);
        txtGiamGia.setBackground(new java.awt.Color(195, 211, 192));
        txtGiamGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiamGiaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("%");

        lbBan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbTienPhaiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lbBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchKH))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiamGia)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTienPhaiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(218, 216, 216));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BÁN HÀNG");

        lbTime.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        lbTime.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTime, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbND, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 40));

        jMenu1.setText("HỆ THỐNG");

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        menuLogout.setText("Đăng xuất");
        menuLogout.setPreferredSize(new java.awt.Dimension(230, 30));
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);
        jMenu1.add(jSeparator1);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        menuExit.setText("Đóng");
        menuExit.setPreferredSize(new java.awt.Dimension(230, 30));
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);
        jMenu1.add(jSeparator8);

        menuChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuChangePass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/changePass.png"))); // NOI18N
        menuChangePass.setText("Đổi mật khẩu");
        menuChangePass.setPreferredSize(new java.awt.Dimension(230, 30));
        menuChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangePassActionPerformed(evt);
            }
        });
        jMenu1.add(menuChangePass);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("QUẢN LÍ");

        menuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/employee.png"))); // NOI18N
        menuNhanVien.setText("Nhân Viên");
        menuNhanVien.setPreferredSize(new java.awt.Dimension(230, 30));
        menuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(menuNhanVien);
        jMenu2.add(jSeparator2);

        menuKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N
        menuKhachHang.setText("Khách hàng");
        menuKhachHang.setPreferredSize(new java.awt.Dimension(230, 30));
        menuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKhachHangActionPerformed(evt);
            }
        });
        jMenu2.add(menuKhachHang);
        jMenu2.add(jSeparator3);

        menuThucDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuThucDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu.png"))); // NOI18N
        menuThucDon.setText("Thực đơn");
        menuThucDon.setPreferredSize(new java.awt.Dimension(230, 30));
        menuThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThucDonActionPerformed(evt);
            }
        });
        jMenu2.add(menuThucDon);
        jMenu2.add(jSeparator5);

        menuLuongNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuLuongNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/salary.png"))); // NOI18N
        menuLuongNV.setText("Lương nhân viên");
        menuLuongNV.setPreferredSize(new java.awt.Dimension(230, 30));
        menuLuongNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLuongNVActionPerformed(evt);
            }
        });
        jMenu2.add(menuLuongNV);
        jMenu2.add(jSeparator6);

        menuBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/table.png"))); // NOI18N
        menuBan.setText("Bàn");
        menuBan.setPreferredSize(new java.awt.Dimension(230, 30));
        menuBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBanActionPerformed(evt);
            }
        });
        jMenu2.add(menuBan);
        jMenu2.add(jSeparator7);

        menuThongKe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thongke.png"))); // NOI18N
        menuThongKe.setText("Thống kê");
        menuThongKe.setPreferredSize(new java.awt.Dimension(230, 30));
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });
        jMenu2.add(menuThongKe);
        jMenu2.add(jSeparator4);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/invoice.png"))); // NOI18N
        jMenuItem1.setText("Hóa đơn");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(230, 30));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("THÔNG TIN");

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/personal.png"))); // NOI18N
        jMenuItem2.setText("Thông tin tài khoản");
        jMenuItem2.setPreferredSize(new java.awt.Dimension(250, 30));
        jMenu3.add(jMenuItem2);
        jMenu3.add(jSeparator9);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tag.png"))); // NOI18N
        jMenuItem3.setText("Chương trình khuyến mãi");
        jMenuItem3.setPreferredSize(new java.awt.Dimension(250, 30));
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("TRỢ GIÚP");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        int XacNhanLogout = JOptionPane.showConfirmDialog(null,
                "Bạn có chắc muốn thoát chương trình không?", "Thông báo xác nhận",
                JOptionPane.YES_NO_OPTION);
        if(XacNhanLogout == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        int XacNhanLogout = JOptionPane.showConfirmDialog(null,
                "Bạn có chắc muốn đăng xuất không?", "Thông báo xác nhận",
                JOptionPane.YES_NO_OPTION);
        if(XacNhanLogout == JOptionPane.YES_OPTION){
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanVienActionPerformed
        jdlNhanVien jdl = new jdlNhanVien(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_menuNhanVienActionPerformed

    private void menuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKhachHangActionPerformed
        jdlKhachHang jdl = new jdlKhachHang(this, true);
        jdl.setVisible(true);
        
        ArrayList<KhachHang> arrKH = BLL.BLLKhachHang.GetAll();
        BLL.BLLKhachHang.DoVaoComboboxKH(arrKH, cbbKhachHang);
    }//GEN-LAST:event_menuKhachHangActionPerformed

    private void menuThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThucDonActionPerformed
        jdlThucDonMon jdl = new jdlThucDonMon(this, true);
        jdl.setVisible(true);

        ArrayList<ThucDon> arrSP = BLL.BLLThucDon.GetAll();
        BLL.BLLThucDon.DoVaoTableThucDonHD(arrSP, tblThucDon);
                
    }//GEN-LAST:event_menuThucDonActionPerformed

    private void menuLuongNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLuongNVActionPerformed
        jdlLuongNhanVien jdl = new jdlLuongNhanVien(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_menuLuongNVActionPerformed

    private void menuBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBanActionPerformed
        jdlBan jdl = new jdlBan(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_menuBanActionPerformed

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        jdlThongKe jdl = new jdlThongKe(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_menuThongKeActionPerformed

    public static boolean Open = false;
    public static String MaNV = "";
    private void menuChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangePassActionPerformed
        Open = false;
        MaNV = lbMaNV.getText();
        jdlChangePass jdl = new jdlChangePass(this, true);
        jdl.setVisible(true);
       
    }//GEN-LAST:event_menuChangePassActionPerformed

    private void txtSearchKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKHKeyReleased

        String TuKhoa = txtSearchKH.getText();
        ArrayList<KhachHang> arrKH = BLL.BLLKhachHang.Find(TuKhoa);
        BLL.BLLKhachHang.DoVaoComboboxKH(arrKH, cbbKhachHang);
    }//GEN-LAST:event_txtSearchKHKeyReleased
    
    void themNuoc(int row) {
        boolean checkmon = true;
        int MonDuocChon = tblThucDon.getSelectedRow();
            if(MonDuocChon < 0){
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn món");
                return;
            }
            String input = JOptionPane.showInputDialog("Nhập số lượng mua");
            if(input.equals("")){
                JOptionPane.showMessageDialog(this, "Nhập số lượng cần mua");
            }else{
                
                tenmon = tblThucDon.getValueAt(MonDuocChon, 1).toString();
                int data = Integer.parseInt(input);
                int soluongmua = data;
                for (int i = 0; i < modeltblOrder.getRowCount(); i++) {
                    if (modeltblOrder.getValueAt(i, 1).toString().equals(tenmon)) {
                        int soluongbd = Integer.parseInt(modeltblOrder.getValueAt(i, 2).toString());
                        soluongbd += soluongmua;
                        modeltblOrder.setValueAt(soluongbd, i, 2);
                        modeltblOrder.setValueAt(soluongbd * Float.parseFloat(modeltblOrder.getValueAt(i, 3).toString()), i, 4);
                        checkmon = false;
                        break;
                    }
                }
                
                if (checkmon) {
                    Vector r = BLL.BLLThucDon.timTenNuocHD(tenmon, soluongmua);
                    modeltblOrder.addRow(r);
                }
                ((Vector) dsMonTungBan.get(row)).clear();
                for (int i = 0; i < modeltblOrder.getRowCount(); i++) {
                    Vector r = new Vector();
                    r.add(modeltblOrder.getValueAt(i, 0));
                    r.add(modeltblOrder.getValueAt(i, 1));
                    r.add(modeltblOrder.getValueAt(i, 2));
                    r.add(modeltblOrder.getValueAt(i, 3));
                    r.add(modeltblOrder.getValueAt(i, 4));
                    ((Vector) dsMonTungBan.get(row)).add(r);
                }
                modeltblBan.setValueAt("Có người", row, 3);
            }
    }
    
    private void tblThucDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThucDonMousePressed
        rowBan = tblBanHD.getSelectedRow();
        if (rowBan < 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bàn", "Thông báo", 2);
            return;
        }
            
        if(evt.getClickCount() == 2){
            themNuoc(rowBan);
            tinhTien();    
        }



        
    }//GEN-LAST:event_tblThucDonMousePressed

    //Tính tiền hóa đơn 
    void tinhTien() {
        float sum = 0;
        for (int i = 0; i < modeltblOrder.getRowCount(); i++) {
            sum += ChuyenDoi.SoDouble(modeltblOrder.getValueAt(i, 4).toString());
        }
        lbTongTien.setText("" + sum );
        float tienGiam = 0;
        
        if (!txtGiamGia.getText().equals("")) {
            float giamGia = (Float.parseFloat(txtGiamGia.getText()));
            tienGiam = sum * giamGia / (float) 100;
        }
        lbTienPhaiTra.setText("" + (sum - tienGiam));
    }
    
    //Tính tiền khách 
    void TinhTienKhach() {
        try {
            float conLai = Float.parseFloat(txtTienKhachDua.getText().trim()) - Float.parseFloat(lbTienPhaiTra.getText());
            if (conLai < 0) {
                lbStatus.setText("Khách đưa không đủ tiền");
                lbStatus.setForeground(Color.red);
                txtTienThua.setText("");
            } else {
                lbStatus.setText("");
                txtTienThua.setText("" + conLai);
            }
        } catch (Exception e) {
            
        }
    }
    
    private void tblBanHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHDMousePressed
            rowBan = tblBanHD.getSelectedRow();
            lbBan.setText(tblBanHD.getValueAt(rowBan, 0).toString());
            if (rowBan >= 0) {
                modeltblOrder.setRowCount(0);
                Vector dsMon = (Vector) dsMonTungBan.get(rowBan);
                for (int i = 0; i < dsMon.size(); i++) {
                    Vector r = (Vector) dsMon.get(i);
                    modeltblOrder.addRow(r);
                }
                tinhTien();
                TinhTienKhach();
            }
        
    }//GEN-LAST:event_tblBanHDMousePressed

    private void btnXoaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonActionPerformed
        int row = tblOrder.getSelectedRow();
        rowBan = tblBanHD.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn dòng nào để xoá", "Thông báo", 1);
            return;
        }

        if (JOptionPane.showConfirmDialog(null, "Bạn muốn xoá " + tblOrder.getValueAt(row, 1) + "?", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            modeltblOrder.removeRow(row);
            if (tblOrder.getRowCount() == 0) {
               modeltblBan.setValueAt("Trống", rowBan, 3); 
            }
            ((Vector) dsMonTungBan.get(rowBan)).remove(row);
            tinhTien();
            TinhTienKhach();
        }
        
    }//GEN-LAST:event_btnXoaMonActionPerformed

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased
        TinhTienKhach();
    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void btnChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBanActionPerformed
        rowBan = tblBanHD.getSelectedRow();
        int index = cbbBan.getSelectedIndex();
        if (rowBan < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn bàn", "Thông báo", 1);
            return;
        }

        if (rowBan == index) {
            JOptionPane.showMessageDialog(null, "Khách đang ở " + tblBanHD.getValueAt(rowBan, 1).toString().toLowerCase() + " rồi nên không thể chuyển!", "Thông báo", 1);
            return;
        }
        
        if (JOptionPane.showConfirmDialog(null, "Bạn muốn chuyển từ " + modeltblBan.getValueAt(rowBan, 1).toString() + " sang " + modeltblBan.getValueAt(index, 1).toString(), "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            dsMonTungBan.set(index, ((Vector) dsMonTungBan.get(rowBan)));
            modeltblOrder.setRowCount(0);
            dsMonTungBan.set(rowBan, new Vector());

            BLLBan.updateTinhTrang(tblBanHD.getValueAt(index, 0).toString(), true);
            BLLBan.updateTinhTrang(tblBanHD.getValueAt(rowBan, 0).toString(), false);
            JOptionPane.showMessageDialog(null, "Chuyển bàn thành công", "Thông báo", 1);
            tblBanHD.setValueAt("Trống", rowBan, 3);
            tblBanHD.setValueAt("Có người", index, 3);
            tblBanHDMousePressed(null);
        }
    }//GEN-LAST:event_btnChuyenBanActionPerformed

    void createNew() {
        txtGiamGia.setText("0");
        lbSoHD.setText(BLL.BLLHoaDon.TaoMaHD());
        dateNgayLapHD.setDate( new java.util.Date());
        lbTongTien.setText("");
        txtTienKhachDua.setText("");
        txtTienThua.setText("");
        lbTienPhaiTra.setText("");
        cbbKhachHang.setSelectedItem("");
        lbBan.setText("");
        modeltblOrder.setRowCount(0);
        lbStatus.setText("");
    }
    
    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        rowBan = tblBanHD.getSelectedRow();
        int rowCount = tblOrder.getRowCount();
        if (rowCount == 0) {
            JOptionPane.showMessageDialog(null, "Hoá đơn rỗng không thể thanh toán", "Thông báo", 2);
            return;
        }
        
        if (txtTienKhachDua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tiền khách đưa không để trống", "Thông báo", 2);
            return;
        }
        
        float tienDua = Float.parseFloat(txtTienKhachDua.getText());
        float tienTraLai = tienDua - Float.parseFloat(lbTienPhaiTra.getText());
        if (tienTraLai < 0) {
            JOptionPane.showMessageDialog(null, "Khách đưa không đủ tiền", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (JOptionPane.showConfirmDialog(null, "Bạn muốn thanh toán hoá đơn " + lbSoHD.getText().trim(), "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
            txtTienThua.setText("" + tienTraLai);
            String mahd = lbSoHD.getText();
            float TongTien = Float.parseFloat(lbTienPhaiTra.getText());
            float GiamGia = 0;
            if (!txtGiamGia.getText().equals("")) {
                GiamGia = Float.parseFloat(txtGiamGia.getText().trim());
            }

            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
            String noiDungFile = "Mã hoá đơn:" + mahd + "\tNgày lập:" + df.format(Calendar.getInstance().getTime()) + "\nTên nhân viên:" + lbMaNV.getText() + "\n" + BLLBan.LayTenBan(tblBanHD.getValueAt(rowBan, 0).toString()) + "\n=========================================================================================================\n" + "Tên món\t\tSố lượng\t\tĐơn giá\t\tThành tiền\n";
  
            HoaDon hd = new HoaDon();
            String MaHD = BLLHoaDon.TaoMaHD();
            hd.setMAHD(MaHD);
            hd.setNGAYLAPHD(new java.util.Date());
            hd.setMANV(lbMaNV.getText());
            hd.setMABAN(lbBan.getText());
            MyCombobox myCBB = (MyCombobox)cbbKhachHang.getSelectedItem();
            int MaKH = myCBB.MaInt();
            hd.setIDKH(MaKH);
            hd.setGIAMGIA(Integer.parseInt(txtGiamGia.getText()));
            hd.setTONGTIEN(TongTien);
            
            BLL.BLLHoaDon.Insert(hd);
            String j = BLLHoaDon.LayHoaDon(MaHD);
            if (j != null) {
                for (int i = 0; i < rowCount; i++) {
                    String TenMon = modeltblOrder.getValueAt(i, 0).toString();
                    int SoLuong = Integer.parseInt(modeltblOrder.getValueAt(i, 2).toString());
                    float DonGia = Float.parseFloat(modeltblOrder.getValueAt(i, 3).toString());
                    
                    CTHD cthd = new CTHD(j , TenMon, DonGia, SoLuong);
                    BLLCTHD.Insert(cthd);
                    noiDungFile += modeltblOrder.getValueAt(i, 1).toString() + "\t\t" + modeltblOrder.getValueAt(i, 2).toString() + "\t\t\t" + modeltblOrder.getValueAt(i, 3).toString() + "\t\t" + modeltblOrder.getValueAt(i, 4).toString() + "\n";
                }
                noiDungFile += "=========================================================================================================\n\t\t\t\t\t\t\tTổng cộng:" + lbTongTien.getText() + "\n\t\t\t\t\t\t\tGiảm giá:" + txtGiamGia.getText() + "%" + "\n\t\t\t\t\t\t\tThành tiền:" + lbTienPhaiTra.getText() + "\n\t\t\t\t\t\t\tTiền khách đưa:" + txtTienKhachDua.getText() + "\n\t\t\t\t\t\t\tTiền thừa:" + txtTienThua.getText();
                createNew();
                j = helper.writeFile(mahd, noiDungFile);
                if (j != null) {
                    BLLBan.updateTinhTrang(tblBanHD.getValueAt(rowBan, 0).toString().trim(), false);
                    modeltblBan.setValueAt("Trống", rowBan, 3);
                    ((Vector) dsMonTungBan.get(rowBan)).clear();
                    JOptionPane.showMessageDialog(null, "Thanh toán thành công", "Thông báo", 1);
                    helper.openFile(mahd);
                }
            }
        }
        
        
        
        
    }//GEN-LAST:event_btnPayActionPerformed

    
    private void txtGiamGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiamGiaKeyReleased
        tinhTien();
    }//GEN-LAST:event_txtGiamGiaKeyReleased

    private void txtSearchMonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchMonKeyReleased
        String TuKhoa = txtSearchMon.getText();
        ArrayList<ThucDon> arr = BLL.BLLThucDon.Find(TuKhoa);
        BLL.BLLThucDon.DoVaoTableThucDonHD(arr, tblThucDon);
    }//GEN-LAST:event_txtSearchMonKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jdlQuanLIHD jdl = new jdlQuanLIHD(this, true);
        jdl.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.JButton btnChuyenBan;
    private button.JButton btnPay;
    private button.JButton btnXoaMon;
    private javax.swing.JComboBox<String> cbbBan;
    private javax.swing.JComboBox<String> cbbKhachHang;
    private com.toedter.calendar.JDateChooser dateNgayLapHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lbBan;
    public javax.swing.JLabel lbMaNV;
    public javax.swing.JLabel lbND;
    private javax.swing.JLabel lbSoHD;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTienPhaiTra;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JMenuItem menuBan;
    private javax.swing.JMenuItem menuChangePass;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuKhachHang;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuLuongNV;
    private javax.swing.JMenuItem menuNhanVien;
    private javax.swing.JMenuItem menuThongKe;
    private javax.swing.JMenuItem menuThucDon;
    private javax.swing.JTable tblBanHD;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblThucDon;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtSearchKH;
    private javax.swing.JTextField txtSearchMon;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JLabel txtTienThua;
    // End of variables declaration//GEN-END:variables
}
